import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// 1. Import the translation tools
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 2. Make the function async so we can fetch data
export default async function RootLayout({ children }) {
  // 3. Get the language and messages from the server
  const locale = await getLocale();
  const messages = await getMessages();

  // 4. Calculate direction (LTR vs RTL) for Hebrew support
  const direction = (locale === "he" || locale === "ar") ? "rtl" : "ltr";

  return (
    // 5. Pass the locale and direction to the HTML tag
    <html lang={locale} dir={direction}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 6. WRAP children in the provider */}
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
